name: "Workflow for Contineous Integration and Deployment."

on: push

jobs:
  ## First download the code
  ## Then Install node init
  ## Then install node modules
  ## then run all the test cases.

  downloading-github-code:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to boss
        run: echo " Hello Boss How may I help you. "

      - name: Download the github Code
        uses: actions/checkout@v3

      - name: Print git repo information
        run: echo " ${{ toJSON(github) }} "

      - name: Installin node.js on machine
        uses: actions/setup-node@v3

      - name: Installing all The node modules
        run: npm ci

      - name: Run all the test case
        run: npm test
